{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a0926d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "CREATE DATABASE EMPLOYEES"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "70cb0496",
   "metadata": {},
   "outputs": [],
   "source": [
    "CREATE TABLE employees(EMP_NO INTEGER,\n",
    "                       EMP_TITLE_ID  VARCHAR(4),\n",
    "                       BIRTH_DATE DATE,\n",
    "                       FIRST_NAME VARCHAR(10),\n",
    "                       LAST_NAME VARCHAR(10),\n",
    "                       SEX VARCHAR(1),\n",
    "                      HIRE_DATE DATE);"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0008075e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
